apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: market-place-purchase
      docker:
        dockerfile: Dockerfile
  local: {}

deploy:
  kubectl:
    manifests:
      - config.yaml
      - deploy.yaml
      - roles.yaml